CREATE TABLE "CBM_SSYSTEM" 
   (	"SSYSTEMID" VARCHAR2(10) NOT NULL ENABLE, 
	"SECOSEQ" NUMBER(12,0) NOT NULL ENABLE, 
	"AUTHID" VARCHAR2(100) NOT NULL ENABLE, 
	"SSYSTEMNM" VARCHAR2(200), 
	"SSYSTEMURL" VARCHAR2(200), 
	"SSYSTEMURL_EXT" VARCHAR2(200), 
	"DSPNO" NUMBER(2,0) NOT NULL ENABLE, 
	"DYSET" TIMESTAMP (6), 
	"DYUPD" TIMESTAMP (6), 
	"USRSET" VARCHAR2(200), 
	"USRUPD" VARCHAR2(200), 
	"PRGUPD" VARCHAR2(30), 
	"VERSION" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "CBM_SSYSTEM_PKC" PRIMARY KEY ("SSYSTEMID")
   ) 